version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs
  nodejs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
